import os

patterns_to_folders = {
    "ferrari 296": "ferrari296gt3",
    "f296": "ferrari296gt3",
    "ferrari 488": "ferrari488gte",
    "ferrari-": "ferrari296gt3",
    "ferrarigtp": "ferrari499p",
    "ferrari 499": "ferrari499p",
    "mclaren 720s": "mclaren720sgt3",
    "720s": "mclaren720sgt3",
    "acuragtp": "acuraarx06gtp",
    "acura-": "acuransxevo22gt3",
    "acura nsx": "acuransxevo22gt3",
    "arx06": "acuraarx06gtp",
    "caddy": "cadillacvseriesrgtp",
    "bmwlmdh": "bmwlmdh",
    "bmwv8": "bmwlmdh",
    "mclaren 570": "mclaren570sgt4",
    "mclarengt3": "mclaren720sgt3",
    "mclaren-": "mclaren720sgt3",
    "mclaren_gts": "mclaren570sgt4",
    "mclarengt4": "mclaren570sgt4",
    "570s": "mclaren570sgt4",
    "porsche 911": "porsche992rgt3",
    "992r": "porsche992rgt3",
    "992gt3": "porsche992rgt3",
    "porsche-": "porsche992rgt3",
    "porschegt3": "porsche992rgt3",
    "porsche rsr": "porsche991rsr",
    "porsche 963": "porsche963gtp",
    "963gtp": "porsche963gtp",
    "porsche963": "porsche963gtp",
    "porsche 718": "porsche718gt4",
    "718gt4": "porsche718gt4",
    "porschegt4": "porsche718gt4",
    "pcup": "porsche992cup",
    "ford mustang": "fordmustanggt3",
    "mustang": "fordmustanggt3",
    "fmgt3": "fordmustanggt3",
    "fordgt3": "fordmustanggt3",
    "ford": "fordmustanggt3",
    "ford_gts": "fordmustanggt3",
    "ford gte": "fordgt2017",
    "ligier": "ligierjsp320",
    "lmp3": "ligierjsp320",
    "bmw m4 gt3": "bmwm4gt3",
    "m4_": "bmwm4gt3",
    "bmw-": "bmwm4gt3",
    "bmw m4 g82": "bmwm4evogt4",
    "g82": "bmwm4evogt4",
    "bmw m8": "bmwm8gte",
    "vette z06": "chevyvettez06rgt3",
    "vette": "chevyvettez06rgt3",
    "corvette-": "chevyvettez06rgt3",
    "vette c8r": "c8rvettegte",
    "c8r": "c8rvettegte",
    "mercedes amg gt3": "mercedesamgevogt3",
    "amg": "mercedesamgevogt3",
    "mercgt3": "mercedesamgevogt3",
    "mercedes-": "mercedesamgevogt3",
    "mercedes_gts": "mercedesamgevogt3",
    "mercedes amg gt4": "mercedesamggt4",
    "amggt4": "mercedesamggt4",
    "mercgt4": "mercedesamggt4",
    "lamborghini": "lamborghinievogt3",
    "lambor": "lamborghinievogt3",
    "huracan": "lamborghinievogt3",
    "lambo-": "lamborghinievogt3",
    "audi": "audir8lmsevo2gt3",
    "audi-": "audir8lmsevo2gt3",
    "r8gt3": "audir8lmsevo2gt3",
    "r8evoii": "audir8lmsevo2gt3",
    "dallara p217": "dallarap217",
    "p217": "dallarap217",
    "lmp2": "dallarap217",
}


patterns_to_circuits = {
    "monza": "Monza",
    "laguna seca": "Laguna Seca",
    "lagunaseca": "Laguna Seca",
    "laguna": "Laguna Seca",
    "spa": "Spa-Francorchamps",
    "suzuka": "Suzuka",
    "lemans": "Le Mans",
    "nos": "Nürburgring Nordschleife",
    "nords": "Nürburgring Nordschleife",
    "nurburgring": "Nürburgring Nordschleife",
    "road america": "Road America",
    "zolder": "Zolder",
    "daytona": "Daytona",
    "watkins": "Watkins Glen",
    "fuji": "Fuji",
}